Update language_strings.json
keatontaylor/alexa-actions pull request #128
Opened 2022-11-27 01:13 UTC by luisrival

Spanish was added in the languages

2022-11-27 19:30 UTC, DEADSEC-SECURITY commented
@luisrival was this tested? Could list the devices that this PR passed and worked?

2022-11-27 21:34 UTC, luisrival commented
It´s working... yes 
as expected..... not shure

It recognize "Si" (Yes) and "No" fine, also I change "custom actions" and " "text": "This is a test of the alexa actions custom skill. Did it work?"  to "acciones personalizadas" and "text": "Esto es una prueba de la skill Notificaciones de alexa, ¿Funcionó?" the translation and it responds correct and in spanish.

But when I run an automation with the notification it doesn't work until I say "acciones personalizadas". I don´t know if it is related with the language or it is an other error.

2022-11-28 01:35 UTC, luisrival commented
Hi

Yes it is tested and is working fine. 
What do you mean with "devices that this PR passed and worked"?

2022-11-28 12:15 UTC, DEADSEC-SECURITY commented
Like did you use a Echo, FireTV or any other amazon device to test this change? @luisrival

2022-11-28 14:16 UTC, luisrival commented
I tested in echo dot, show and it works fine. Also I tested in sonos one and bean connected with alexa, but in these the notification is trigger only when I trigger manually saying "acciones personalizadas" I don´t know if is a languaje problem or the skill or alexa

2022-11-29 15:48 UTC, DEADSEC-SECURITY requested changes
Your missing a file for the new language. Please check the skill-manifests folder for reference and before creating make sure the skill-manifest is according to amazon documentation otherwise it might not recognize the language properly. This should fix the issue you refered.

2022-11-29 15:48 UTC, DEADSEC-SECURITY commented on lambda/language_strings.json
> +		"ERROR_404": "Parece que no puedo encontrar la entidad de texto de entrada. Verifica que lo hayas agregado a Home Assistant e inténtalo de nuevo",
Please fix indentation

2022-11-29 22:43 UTC, DEADSEC-SECURITY commented
Yup you're just missing the skill manifest for the es language now.

2022-12-16 16:20 UTC, DEADSEC-SECURITY commented
Any news?

2022-12-16 18:52 UTC, DEADSEC-SECURITY requested changes
Missing skill manifest

2022-12-27 13:49 UTC, DEADSEC-SECURITY commented
Due to changes in the skill this PR needs further development to work

2022-12-27 13:49 UTC, closed without merging